name: CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: black
        uses: lgeiger/black-action@v1.0.1
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
